In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from collections import Counter

In [2]:
data = pd.read_csv('movie_bd_v5.csv')
data.sample(5)

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year
1864,tt0203019,32000000,48814909,Men of Honor,Robert De Niro|Cuba Gooding Jr.|Charlize Thero...,"George Tillman, Jr.",History is made by those who break the rules.,Against formidable odds -- and an old-school d...,129,Drama,Fox 2000 Pictures,9/13/2000,7.0,2000
1798,tt0499554,10000000,20342161,Reno 911!: Miami,Lennie Loftin|Danny DeVito|Ben Garant|Carlos A...,Ben Garant,"In a time of crisis, America will call Reno 911!",A rag-tag team of Reno cops are called in to s...,84,Action|Adventure|Comedy|Crime,20th Century Fox,2/23/2007,5.8,2007
1223,tt1951261,103000000,362000072,The Hangover Part III,Bradley Cooper|Ed Helms|Zach Galifianakis|Just...,Todd Phillips,It all ends.,"This time, there's no wedding. No bachelor par...",100,Comedy,Legendary Pictures|Green Hat Films,5/23/2013,6.0,2013
1398,tt0398165,82000000,190320568,The Longest Yard,Adam Sandler|Chris Rock|Burt Reynolds|Michael ...,Peter Segal,"If you can't get out, get even.","Pro quarter-back, Paul Crewe and former colleg...",113,Comedy|Drama,Paramount Pictures|Columbia Pictures Corporati...,5/19/2005,6.2,2005
1058,tt1535438,30000000,114281051,Hope Springs,Meryl Streep|Steve Carell|Tommy Lee Jones|Jean...,David Frankel,"Sometimes to keep the magic, you need to learn...","After thirty years of marriage, a middle-aged ...",100,Drama|Comedy|Romance,Columbia Pictures|Mandate Pictures|Escape Arti...,8/7/2012,5.6,2012

In [3]:
data.describe()

             budget       revenue      runtime  vote_average  release_year
count  1.889000e+03  1.889000e+03  1889.000000   1889.000000   1889.000000
mean   5.431083e+07  1.553653e+08   109.658549      6.140762   2007.860773
std    4.858721e+07  2.146698e+08    18.017041      0.764763      4.468841
min    5.000000e+06  2.033165e+06    63.000000      3.300000   2000.000000
25%    2.000000e+07  3.456058e+07    97.000000      5.600000   2004.000000
50%    3.800000e+07  8.361541e+07   107.000000      6.100000   2008.000000
75%    7.200000e+07  1.782626e+08   120.000000      6.600000   2012.000000
max    3.800000e+08  2.781506e+09   214.000000      8.100000   2015.000000

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1889 entries, 0 to 1888
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   imdb_id               1889 non-null   object
 1   budget                1889 non-null   int64
 2   revenue               1889 non-null   int64
 3   original_title        1889 non-null   object
 4   cast                  1889 non-null   object
 5   director              1889 non-null   object
 6   tagline               1889 non-null   object
 7   overview              1889 non-null   object
 8   runtime               1889 non-null   int64
 9   genres                1889 non-null   object
 10  production_companies  1889 non-null   object
 11  release_date          1889 non-null   object
 12  vote_average          1889 non-null   float64
 13  release_year          1889 non-null   int64
dtypes: float64(1), int64(4), object(9)
memory usage: 206.7+ KB

Вопрос 1. У какого фильма из списка самый большой бюджет?

In [103]:
data1 = pd.read_csv('movie_bd_v5.csv')
data1.groupby(['original_title'])['budget'].max().sort_values(ascending=False)

original_title
Pirates of the Caribbean: On Stranger Tides    380000000
Pirates of the Caribbean: At World's End       300000000
Avengers: Age of Ultron                        280000000
Tangled                                        260000000
John Carter                                    260000000
                                                 ...
Spring Breakers                                  5000000
The Last Exorcism Part II                        5000000
Apollo 18                                        5000000
Paranormal Activity: The Marked Ones             5000000
Clerks II                                        5000000
Name: budget, Length: 1887, dtype: int64

Вопрос 2. Какой из фильмов самый длительный (в минутах)?

In [104]:
data2 = pd.read_csv('movie_bd_v5.csv')
data2.groupby(['original_title'])['runtime'].max().sort_values(ascending=False)

original_title
Gods and Generals                                214
The Lord of the Rings: The Return of the King    201
Grindhouse                                       191
King Kong                                        187
Pearl Harbor                                     183
                                                ...
Valiant                                           76
Home on the Range                                 76
The Jungle Book 2                                 72
Return to Never Land                              72
Winnie the Pooh                                   63
Name: runtime, Length: 1887, dtype: int64

Вопрос 3. Какой из фильмов самый короткий (в минутах)?

In [106]:
data3 = pd.read_csv('movie_bd_v5.csv')
data3.groupby(['original_title'])['runtime'].min().sort_values()

original_title
Winnie the Pooh                                   63
Return to Never Land                              72
The Jungle Book 2                                 72
Home on the Range                                 76
Valiant                                           76
                                                ...
Pearl Harbor                                     183
King Kong                                        187
Grindhouse                                       191
The Lord of the Rings: The Return of the King    201
Gods and Generals                                214
Name: runtime, Length: 1887, dtype: int64

Вопрос 4. Какова средняя длительность фильмов?

In [11]:
data['runtime'].mean()

109.6585494970884

Вопрос 5. Каково медианное значение длительности фильмов?

In [12]:
data['runtime'].median()

107.0

Внимание! Здесь и далее под «прибылью» или «убытками» понимается разность между сборами и бюджетом фильма. Прибыль = сборы - бюджет (profit = revenue - budget).

Вопрос 6. Какой фильм самый прибыльный?

In [13]:
data['profit'] = data['revenue'] - data['budget']
data.sort_values(['profit'], ascending=False)

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit
239,tt0499549,237000000,2781505847,Avatar,Sam Worthington|Zoe Saldana|Sigourney Weaver|S...,James Cameron,Enter the World of Pandora.,"In the 22nd century, a paraplegic Marine is di...",162,Action|Adventure|Fantasy|Science Fiction,Ingenious Film Partners|Twentieth Century Fox ...,12/10/2009,7.1,2009,2544505847
3,tt2488496,200000000,2068178225,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,J.J. Abrams,Every generation has a story.,Thirty years after defeating the Galactic Empi...,136,Action|Adventure|Science Fiction|Fantasy,Lucasfilm|Truenorth Productions|Bad Robot,12/15/2015,7.5,2015,1868178225
0,tt0369610,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,Colin Trevorrow,The park is open.,Twenty-two years after the events of Jurassic ...,124,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,6/9/2015,6.5,2015,1363528810
4,tt2820852,190000000,1506249360,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,James Wan,Vengeance Hits Home,Deckard Shaw seeks revenge against Dominic Tor...,137,Action|Crime|Thriller,Universal Pictures|Original Film|Media Rights ...,4/1/2015,7.3,2015,1316249360
970,tt0848228,220000000,1519557910,The Avengers,Robert Downey Jr.|Chris Evans|Mark Ruffalo|Chr...,Joss Whedon,Some assembly required.,When an unexpected enemy emerges and threatens...,143,Science Fiction|Action|Adventure,Marvel Studios,4/25/2012,7.3,2012,1299557910
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1464,tt0424095,149000000,64459316,Flushed Away,Hugh Jackman|Kate Winslet|Ian McKellen|Jean Re...,David Bowers|Sam Fell,Someone's Going Down,"London high-society mouse, Roddy is flushed do...",85,Adventure|Animation|Comedy|Family,Aardman Animations|DreamWorks Animation,10/22/2006,6.0,2006,-84540684
958,tt0180052,100000000,7103973,The Adventures of Pluto Nash,Eddie Murphy|Randy Quaid|Rosario Dawson|Joe Pa...,Ron Underwood,Action's future has arrived...,"The year is 2087, the setting is the moon. Edd...",95,Action|Comedy|Science Fiction,Village Roadshow Pictures|Castle Rock Entertai...,8/15/2002,4.6,2002,-92896027
809,tt1305591,150000000,38992758,Mars Needs Moms,Seth Green|Joan Cusack|Dan Fogler|Breckin Meye...,Simon Wells,Mom needs a little space.,"When Martians suddenly abduct his mom, mischie...",88,Adventure|Animation|Family,Walt Disney Animation Studios,3/9/2011,5.5,2011,-111007242
1616,tt0318974,145000000,25819961,The Alamo,Dennis Quaid|Billy Bob Thornton|Jason Patric|P...,John Lee Hancock,You will never forget,Based on the 1836 standoff between a group of ...,137,Western|History|War,Imagine Entertainment|Touchstone Pictures,4/7/2004,5.9,2004,-119180039
1245,tt1210819,255000000,89289910,The Lone Ranger,Johnny Depp|Armie Hammer|William Fichtner|Hele...,Gore Verbinski,Never Take Off the Mask,The Texas Rangers chase down a gang of outlaws...,149,Action|Adventure|Western,Walt Disney Pictures|Jerry Bruckheimer Films|I...,7/3/2013,6.0,2013,-165710090

Вопрос 7. Какой фильм самый убыточный?

In [14]:
data.sort_values(['profit'])

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit
1245,tt1210819,255000000,89289910,The Lone Ranger,Johnny Depp|Armie Hammer|William Fichtner|Hele...,Gore Verbinski,Never Take Off the Mask,The Texas Rangers chase down a gang of outlaws...,149,Action|Adventure|Western,Walt Disney Pictures|Jerry Bruckheimer Films|I...,7/3/2013,6.0,2013,-165710090
1616,tt0318974,145000000,25819961,The Alamo,Dennis Quaid|Billy Bob Thornton|Jason Patric|P...,John Lee Hancock,You will never forget,Based on the 1836 standoff between a group of ...,137,Western|History|War,Imagine Entertainment|Touchstone Pictures,4/7/2004,5.9,2004,-119180039
809,tt1305591,150000000,38992758,Mars Needs Moms,Seth Green|Joan Cusack|Dan Fogler|Breckin Meye...,Simon Wells,Mom needs a little space.,"When Martians suddenly abduct his mom, mischie...",88,Adventure|Animation|Family,Walt Disney Animation Studios,3/9/2011,5.5,2011,-111007242
958,tt0180052,100000000,7103973,The Adventures of Pluto Nash,Eddie Murphy|Randy Quaid|Rosario Dawson|Joe Pa...,Ron Underwood,Action's future has arrived...,"The year is 2087, the setting is the moon. Edd...",95,Action|Comedy|Science Fiction,Village Roadshow Pictures|Castle Rock Entertai...,8/15/2002,4.6,2002,-92896027
1464,tt0424095,149000000,64459316,Flushed Away,Hugh Jackman|Kate Winslet|Ian McKellen|Jean Re...,David Bowers|Sam Fell,Someone's Going Down,"London high-society mouse, Roddy is flushed do...",85,Adventure|Animation|Comedy|Family,Aardman Animations|DreamWorks Animation,10/22/2006,6.0,2006,-84540684
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
970,tt0848228,220000000,1519557910,The Avengers,Robert Downey Jr.|Chris Evans|Mark Ruffalo|Chr...,Joss Whedon,Some assembly required.,When an unexpected enemy emerges and threatens...,143,Science Fiction|Action|Adventure,Marvel Studios,4/25/2012,7.3,2012,1299557910
4,tt2820852,190000000,1506249360,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,James Wan,Vengeance Hits Home,Deckard Shaw seeks revenge against Dominic Tor...,137,Action|Crime|Thriller,Universal Pictures|Original Film|Media Rights ...,4/1/2015,7.3,2015,1316249360
0,tt0369610,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,Colin Trevorrow,The park is open.,Twenty-two years after the events of Jurassic ...,124,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,6/9/2015,6.5,2015,1363528810
3,tt2488496,200000000,2068178225,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,J.J. Abrams,Every generation has a story.,Thirty years after defeating the Galactic Empi...,136,Action|Adventure|Science Fiction|Fantasy,Lucasfilm|Truenorth Productions|Bad Robot,12/15/2015,7.5,2015,1868178225
239,tt0499549,237000000,2781505847,Avatar,Sam Worthington|Zoe Saldana|Sigourney Weaver|S...,James Cameron,Enter the World of Pandora.,"In the 22nd century, a paraplegic Marine is di...",162,Action|Adventure|Fantasy|Science Fiction,Ingenious Film Partners|Twentieth Century Fox ...,12/10/2009,7.1,2009,2544505847

Вопрос 8. У скольких фильмов из датасета объем сборов оказался выше бюджета?

In [15]:
len(data[data['revenue']>data['budget']])

1478

Вопрос 9. Какой фильм оказался самым кассовым в 2008 году?

In [16]:
data[data['release_year'] == 2008].sort_values(['revenue'], ascending=False)

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit
599,tt0468569,185000000,1001921825,The Dark Knight,Christian Bale|Michael Caine|Heath Ledger|Aaro...,Christopher Nolan,Why So Serious?,Batman raises the stakes in his war on crime. ...,152,Drama|Action|Crime|Thriller,DC Comics|Legendary Pictures|Warner Bros.|Syncopy,7/16/2008,8.1,2008,816921825
603,tt0367882,185000000,786636033,Indiana Jones and the Kingdom of the Crystal S...,Harrison Ford|Cate Blanchett|Shia LaBeouf|Ray ...,Steven Spielberg,The adventure continues . . .,"Set during the Cold War, the Soviets â€“ led b...",122,Adventure|Action,Lucasfilm|Paramount Pictures,5/21/2008,5.6,2008,601636033
606,tt0441773,130000000,631744560,Kung Fu Panda,Jack Black|Dustin Hoffman|Angelina Jolie|Jacki...,Mark Osborne|John Stevenson,Prepare for awesomeness.,"When the Valley of Peace is threatened, lazy P...",90,Animation|Family,DreamWorks Animation,6/4/2008,6.8,2008,501744560
621,tt0448157,150000000,624029371,Hancock,Will Smith|Charlize Theron|Jason Bateman|Jae H...,Peter Berg,Bad Behavior. Bad Attitude. Real Hero.,Hancock is a down-and-out superhero who's forc...,92,Fantasy|Action,Columbia Pictures|Weed Road Pictures|Forward P...,7/1/2008,6.0,2008,474029371
607,tt0795421,52000000,609841637,Mamma Mia!,Meryl Streep|Pierce Brosnan|Amanda Seyfried|Co...,Phyllida Lloyd,Take a trip down the aisle you'll never forget,"Set on an idyllic Greek island, the plot serve...",108,Comedy|Romance,Universal Pictures|Internationale Filmprodukti...,6/30/2008,6.2,2008,557841637
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
708,tt0486674,25000000,6673422,What Just Happened,Bruce Willis|Robert De Niro|Sean Penn|Robin Wr...,Barry Levinson,Admit nothing.,During the course of an ordinary week in Holly...,104,Comedy|Drama,2929 Productions|Linson Entertainment|Art Lins...,10/17/2008,5.1,2008,-18326578
673,tt0800241,15000000,5926410,Transsiberian,Woody Harrelson|Emily Mortimer|Kate Mara|Eduar...,Brad Anderson,You can't escape your lies.,A Trans-Siberian train journey from China to M...,111,Thriller|Crime|Mystery,Lietuvos Kinostudija|Scout Productions|Telecin...,1/18/2008,6.3,2008,-9073590
702,tt0844286,20000000,5530764,The Brothers Bloom,Rachel Weisz|Adrien Brody|Mark Ruffalo|Rinko K...,Rian Johnson,They'd never let the truth come between them.,The Brothers Bloom are the best con men in the...,114,Adventure|Comedy|Drama|Romance,The Weinstein Company|Summit Entertainment|End...,9/9/2008,6.8,2008,-14469236
711,tt0805570,15000000,3533227,The Midnight Meat Train,Bradley Cooper|Vinnie Jones|Brooke Shields|Les...,RyÃ»hei Kitamura,The most terrifying ride you'll ever take,The photographer Leon lives with his girlfrien...,98,Mystery|Drama|Crime|Thriller|Horror,Lions Gate Films|Lakeshore Entertainment|Green...,8/7/2008,5.7,2008,-11466773
712,tt0490181,8000000,2033165,Mutant Chronicles,Ron Perlman|Thomas Jane|Devon Aoki|Sean Pertwe...,Simon Hunter,Welcome to the 23rd century. The new dark ages.,It's the year 2707. Earth's natural resources ...,111,Action|Adventure|Horror|Science Fiction,Isle of Man Film|Edward R. Pressman Film|Parad...,8/7/2008,5.1,2008,-5966835

Вопрос 10. Самый убыточный фильм за период с 2012 по 2014 годы (включительно)?

In [17]:
data[(data['release_year'] <= 2014) & (data['release_year'] >= 2012)].sort_values(['profit'])

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit
1245,tt1210819,255000000,89289910,The Lone Ranger,Johnny Depp|Armie Hammer|William Fichtner|Hele...,Gore Verbinski,Never Take Off the Mask,The Texas Rangers chase down a gang of outlaws...,149,Action|Adventure|Western,Walt Disney Pictures|Jerry Bruckheimer Films|I...,7/3/2013,6.0,2013,-165710090
1214,tt0790736,130000000,61648500,R.I.P.D.,Jeff Bridges|Ryan Reynolds|Kevin Bacon|Stephan...,Robert Schwentke,To protect and serve the living,A recently slain cop joins a team of undead po...,96,Fantasy|Action|Comedy|Crime,Universal Pictures|Original Film|Dark Horse En...,7/18/2013,5.3,2013,-68351500
1007,tt1374992,60000000,8106475,Upside Down,Kirsten Dunst|Jim Sturgess|Timothy Spall|James...,Juan Diego Solanas,Two worlds. One future.,In an alternate universe where twinned worlds ...,104,Romance|Science Fiction|Drama|Fantasy,Onyx Films|Studio 37|Jouror Productions|France...,9/27/2012,6.1,2012,-51893525
1302,tt0884726,70000000,18662027,Legends of Oz: Dorothy's Return,Lea Michele|Dan Aykroyd|Patrick Stewart|Hugh D...,Dan St. Pierre,There's trouble in OZ...,"Dorothy wakes up in post-tornado Kansas, only ...",88,Animation|Music|Family,Prana Animation Studios|Summertime Entertainment,6/13/2013,6.1,2013,-51337973
1235,tt1308729,55000000,9489829,Bullet to the Head,Sylvester Stallone|Sung Kang|Sarah Shahi|Adewa...,Walter Hill,Revenge Never Gets Old.,"After watching their respective partners die, ...",92,Action|Crime|Thriller,Dark Castle Entertainment|After Dark Films|IM ...,1/31/2013,5.2,2013,-45510171
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1189,tt1690953,76000000,970761885,Despicable Me 2,Steve Carell|Kristen Wiig|Benjamin Bratt|Miran...,Pierre Coffin|Chris Renaud,Back 2 Work,Gru is recruited by the Anti-Villain League to...,98,Animation|Comedy|Family,Universal Pictures|Illumination Entertainment,6/25/2013,7.0,2013,894761885
974,tt1074638,200000000,1108561013,Skyfall,Daniel Craig|Judi Dench|Javier Bardem|Ralph Fi...,Sam Mendes,Think on your sins.,When Bond's latest assignment goes gravely wro...,143,Action|Adventure|Thriller,Columbia Pictures,10/25/2012,6.8,2012,908561013
1180,tt1300854,200000000,1215439994,Iron Man 3,Robert Downey Jr.|Gwyneth Paltrow|Guy Pearce|D...,Shane Black,Unleash the power behind the armor.,When Tony Stark's world is torn apart by a for...,130,Action|Adventure|Science Fiction,Marvel Studios,4/18/2013,6.9,2013,1015439994
1177,tt2294629,150000000,1274219009,Frozen,Kristen Bell|Idina Menzel|Jonathan Groff|Josh ...,Chris Buck|Jennifer Lee,Only the act of true love will thaw a frozen h...,Young princess Anna of Arendelle dreams about ...,102,Animation|Adventure|Family,Walt Disney Pictures|Walt Disney Animation Stu...,11/27/2013,7.5,2013,1124219009
970,tt0848228,220000000,1519557910,The Avengers,Robert Downey Jr.|Chris Evans|Mark Ruffalo|Chr...,Joss Whedon,Some assembly required.,When an unexpected enemy emerges and threatens...,143,Science Fiction|Action|Adventure,Marvel Studios,4/25/2012,7.3,2012,1299557910

Вопрос 11. Какого жанра фильмов больше всего?

In [18]:
gen_count = []
for i in data['genres']:
    gen_count.append(i.split(sep='|'))
c = Counter(gen for gen_list in gen_count for gen in gen_list)
print(c)

Counter({'Drama': 782, 'Comedy': 683, 'Thriller': 596, 'Action': 582, 'Adventure': 415, 'Crime': 315, 'Romance': 308, 'Family': 260, 'Science Fiction': 248, 'Fantasy': 222, 'Horror': 176, 'Mystery': 168, 'Animation': 139, 'Music': 64, 'History': 62, 'War': 58, 'Western': 19, 'Documentary': 8, 'Foreign': 2})

Вопрос 12. Фильмы какого жанра чаще всего становятся прибыльными?

In [107]:
profit_genres = []
for j in data['profit']:
    for i in data['genres']:
        profit_genres.append(i.split(sep='|'))
pg = Counter(gen for gen_list in profit_genres for gen in gen_list)
print(pg)

Counter({'Drama': 1477198, 'Comedy': 1290187, 'Thriller': 1125844, 'Action': 1099398, 'Adventure': 783935, 'Crime': 595035, 'Romance': 581812, 'Family': 491140, 'Science Fiction': 468472, 'Fantasy': 419358, 'Horror': 332464, 'Mystery': 317352, 'Animation': 262571, 'Music': 120896, 'History': 117118, 'War': 109562, 'Western': 35891, 'Documentary': 15112, 'Foreign': 3778})

Вопрос 13. У какого режиссёра самые большие суммарные кассовые сборы?

In [20]:
data.groupby(['director'])['revenue'].sum().sort_values(ascending=False)

director
Peter Jackson        6490593685
Christopher Nolan    4167548502
David Yates          4154295625
Michael Bay          3886938960
J.J. Abrams          3579169916
                        ...
David MichÃ´d           2295423
Steven Shainberg        2281089
Paul Schrader           2062066
Keanu Reeves            2054941
Simon Hunter            2033165
Name: revenue, Length: 957, dtype: int64

Вопрос 14. Какой режиссер снял больше всего фильмов в стиле Action?

In [21]:
data14 = pd.read_csv('movie_bd_v5.csv')
data14['genres'] = data14['genres'].str.split('|')
data14['director'] = data14['director'].str.split('|')
data14 = data14.explode('genres')
data14 = data14.explode('director')
display(data14)
data14_res = data14[data14['genres'] == 'Action'].groupby(['director'])['genres'].count().sort_values(ascending=False)
display(data14_res)

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year
0,tt0369610,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,Colin Trevorrow,The park is open.,Twenty-two years after the events of Jurassic ...,124,Action,Universal Studios|Amblin Entertainment|Legenda...,6/9/2015,6.5,2015
0,tt0369610,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,Colin Trevorrow,The park is open.,Twenty-two years after the events of Jurassic ...,124,Adventure,Universal Studios|Amblin Entertainment|Legenda...,6/9/2015,6.5,2015
0,tt0369610,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,Colin Trevorrow,The park is open.,Twenty-two years after the events of Jurassic ...,124,Science Fiction,Universal Studios|Amblin Entertainment|Legenda...,6/9/2015,6.5,2015
0,tt0369610,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,Colin Trevorrow,The park is open.,Twenty-two years after the events of Jurassic ...,124,Thriller,Universal Studios|Amblin Entertainment|Legenda...,6/9/2015,6.5,2015
1,tt1392190,150000000,378436354,Mad Max: Fury Road,Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...,George Miller,What a Lovely Day.,An apocalyptic story set in the furthest reach...,120,Action,Village Roadshow Pictures|Kennedy Miller Produ...,5/13/2015,7.1,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1886,tt0131704,76000000,35134820,The Adventures of Rocky & Bullwinkle,Rene Russo|Jason Alexander|Piper Perabo|Randy ...,Des McAnuff,This summer it's not the same old bull.,Rocky and Bullwinkle have been living off the ...,88,Comedy,Universal Pictures|Capella International|KC Me...,6/30/2000,4.0,2000
1886,tt0131704,76000000,35134820,The Adventures of Rocky & Bullwinkle,Rene Russo|Jason Alexander|Piper Perabo|Randy ...,Des McAnuff,This summer it's not the same old bull.,Rocky and Bullwinkle have been living off the ...,88,Family,Universal Pictures|Capella International|KC Me...,6/30/2000,4.0,2000
1887,tt0162983,40000000,36037909,Hanging Up,Meg Ryan|Diane Keaton|Lisa Kudrow|Walter Matth...,Diane Keaton,Every family has a few hang-ups.,A trio of sisters bond over their ambivalence ...,94,Comedy,Laurence Mark Productions|Columbia Pictures Co...,2/16/2000,5.2,2000
1887,tt0162983,40000000,36037909,Hanging Up,Meg Ryan|Diane Keaton|Lisa Kudrow|Walter Matth...,Diane Keaton,Every family has a few hang-ups.,A trio of sisters bond over their ambivalence ...,94,Drama,Laurence Mark Productions|Columbia Pictures Co...,2/16/2000,5.2,2000
1888,tt0163676,15000000,5217498,The In Crowd,Susan Ward|Lori Heuring|Matthew Settle|Nathan ...,Mary Lambert,What would you do to get in?,A mentally disturbed young woman takes a job a...,105,Thriller,Warner Bros. Pictures,7/19/2000,5.2,2000

director
Robert Rodriguez      9
Paul W.S. Anderson    7
Michael Bay           7
Ridley Scott          6
Antoine Fuqua         6
                     ..
Joe Cornish           1
Roger Spottiswoode    1
Jimmy Hayward         1
Jim Gillespie         1
Jon Avnet             1
Name: genres, Length: 364, dtype: int64

Вопрос 15. Фильмы с каким актером принесли самые высокие кассовые сборы в 2012 году?

In [22]:
data15 = pd.read_csv('movie_bd_v5.csv')
data15['cast'] = data15['cast'].str.split('|')
data15_cast = data15.explode('cast')
display(data15_cast)
data15_res = data15_cast[data15_cast['release_year'] == 2012].groupby(['cast'])['revenue'].sum().sort_values(ascending=False)
display(data15_res)

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year
0,tt0369610,150000000,1513528810,Jurassic World,Chris Pratt,Colin Trevorrow,The park is open.,Twenty-two years after the events of Jurassic ...,124,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,6/9/2015,6.5,2015
0,tt0369610,150000000,1513528810,Jurassic World,Bryce Dallas Howard,Colin Trevorrow,The park is open.,Twenty-two years after the events of Jurassic ...,124,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,6/9/2015,6.5,2015
0,tt0369610,150000000,1513528810,Jurassic World,Irrfan Khan,Colin Trevorrow,The park is open.,Twenty-two years after the events of Jurassic ...,124,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,6/9/2015,6.5,2015
0,tt0369610,150000000,1513528810,Jurassic World,Vincent D'Onofrio,Colin Trevorrow,The park is open.,Twenty-two years after the events of Jurassic ...,124,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,6/9/2015,6.5,2015
0,tt0369610,150000000,1513528810,Jurassic World,Nick Robinson,Colin Trevorrow,The park is open.,Twenty-two years after the events of Jurassic ...,124,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,6/9/2015,6.5,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1888,tt0163676,15000000,5217498,The In Crowd,Susan Ward,Mary Lambert,What would you do to get in?,A mentally disturbed young woman takes a job a...,105,Thriller,Warner Bros. Pictures,7/19/2000,5.2,2000
1888,tt0163676,15000000,5217498,The In Crowd,Lori Heuring,Mary Lambert,What would you do to get in?,A mentally disturbed young woman takes a job a...,105,Thriller,Warner Bros. Pictures,7/19/2000,5.2,2000
1888,tt0163676,15000000,5217498,The In Crowd,Matthew Settle,Mary Lambert,What would you do to get in?,A mentally disturbed young woman takes a job a...,105,Thriller,Warner Bros. Pictures,7/19/2000,5.2,2000
1888,tt0163676,15000000,5217498,The In Crowd,Nathan Bexton,Mary Lambert,What would you do to get in?,A mentally disturbed young woman takes a job a...,105,Thriller,Warner Bros. Pictures,7/19/2000,5.2,2000
1888,tt0163676,15000000,5217498,The In Crowd,Tess Harper,Mary Lambert,What would you do to get in?,A mentally disturbed young woman takes a job a...,105,Thriller,Warner Bros. Pictures,7/19/2000,5.2,2000

cast
Chris Hemsworth      2027450773
Denis Leary          1629460639
Anne Hathaway        1522851057
Chris Evans          1519557910
Robert Downey Jr.    1519557910
                        ...
Jason Bateman           3428048
Danny Huston            2106557
Sami Gayle              2106557
Josh Lucas              2106557
Nicolas Cage            2106557
Name: revenue, Length: 466, dtype: int64

Вопрос 16. Какой актер снялся в большем количестве высокобюджетных фильмов?

In [23]:
data16 = data15_cast.copy()
data16_res = data16[data16['budget'] > data16['budget'].mean()].groupby(['cast'])['cast'].count().sort_values(ascending=False)
display(data16_res)

cast
Matt Damon           18
Adam Sandler         17
Angelina Jolie       16
Eddie Murphy         15
Samuel L. Jackson    15
                     ..
Leslie Bibb           1
Leonard Nimoy         1
Lennie James          1
Lena Olin             1
50 Cent               1
Name: cast, Length: 1505, dtype: int64

Вопрос 17. В фильмах какого жанра больше всего снимался Nicolas Cage?

In [24]:
data17 = pd.read_csv('movie_bd_v5.csv')
data17['genres'] = data17['genres'].str.split('|')
data17['cast'] = data17['cast'].str.split('|')
data17 = data17.explode('genres')
data17 = data17.explode('cast')
display(data17)
data17res = data17[data17['cast'] == 'Nicolas Cage'].groupby(['genres'])['cast'].count().sort_values(ascending=False)
display(data17res)

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year
0,tt0369610,150000000,1513528810,Jurassic World,Chris Pratt,Colin Trevorrow,The park is open.,Twenty-two years after the events of Jurassic ...,124,Action,Universal Studios|Amblin Entertainment|Legenda...,6/9/2015,6.5,2015
0,tt0369610,150000000,1513528810,Jurassic World,Bryce Dallas Howard,Colin Trevorrow,The park is open.,Twenty-two years after the events of Jurassic ...,124,Action,Universal Studios|Amblin Entertainment|Legenda...,6/9/2015,6.5,2015
0,tt0369610,150000000,1513528810,Jurassic World,Irrfan Khan,Colin Trevorrow,The park is open.,Twenty-two years after the events of Jurassic ...,124,Action,Universal Studios|Amblin Entertainment|Legenda...,6/9/2015,6.5,2015
0,tt0369610,150000000,1513528810,Jurassic World,Vincent D'Onofrio,Colin Trevorrow,The park is open.,Twenty-two years after the events of Jurassic ...,124,Action,Universal Studios|Amblin Entertainment|Legenda...,6/9/2015,6.5,2015
0,tt0369610,150000000,1513528810,Jurassic World,Nick Robinson,Colin Trevorrow,The park is open.,Twenty-two years after the events of Jurassic ...,124,Action,Universal Studios|Amblin Entertainment|Legenda...,6/9/2015,6.5,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1888,tt0163676,15000000,5217498,The In Crowd,Susan Ward,Mary Lambert,What would you do to get in?,A mentally disturbed young woman takes a job a...,105,Thriller,Warner Bros. Pictures,7/19/2000,5.2,2000
1888,tt0163676,15000000,5217498,The In Crowd,Lori Heuring,Mary Lambert,What would you do to get in?,A mentally disturbed young woman takes a job a...,105,Thriller,Warner Bros. Pictures,7/19/2000,5.2,2000
1888,tt0163676,15000000,5217498,The In Crowd,Matthew Settle,Mary Lambert,What would you do to get in?,A mentally disturbed young woman takes a job a...,105,Thriller,Warner Bros. Pictures,7/19/2000,5.2,2000
1888,tt0163676,15000000,5217498,The In Crowd,Nathan Bexton,Mary Lambert,What would you do to get in?,A mentally disturbed young woman takes a job a...,105,Thriller,Warner Bros. Pictures,7/19/2000,5.2,2000
1888,tt0163676,15000000,5217498,The In Crowd,Tess Harper,Mary Lambert,What would you do to get in?,A mentally disturbed young woman takes a job a...,105,Thriller,Warner Bros. Pictures,7/19/2000,5.2,2000

genres
Action             17
Thriller           15
Drama              12
Crime              10
Fantasy             8
Adventure           7
Comedy              6
Science Fiction     4
Mystery             3
Family              3
Animation           3
History             2
War                 1
Romance             1
Horror              1
Name: cast, dtype: int64

Вопрос 18. Самый убыточный фильм от Paramount Pictures?

In [25]:
data18 = pd.read_csv('movie_bd_v5.csv')
data18['production_companies'] = data18['production_companies'].str.split('|')
data18 = data18.explode('production_companies')
data18['profit'] = data18['revenue'] - data18['budget']
data18[data18['production_companies'] == 'Paramount Pictures'].sort_values(['profit'])

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit
925,tt0267626,100000000,35168966,K-19: The Widowmaker,Harrison Ford|Liam Neeson|Peter Sarsgaard|Joss...,Kathryn Bigelow,Fate has found its hero.,When Russia's first nuclear submarine malfunct...,138,Thriller|Drama|History,Paramount Pictures,7/19/2002,6.0,2002,-64831034
1123,tt0300556,80000000,19480739,Timeline,Paul Walker|Frances O'Connor|Gerard Butler|Bil...,Richard Donner,They had to travel into the past to save the f...,A group of archaeological students become trap...,116,Action|Adventure|Science Fiction,Paramount Pictures,11/26/2003,5.1,2003,-60519261
1722,tt0435705,70000000,18211013,Next,Nicolas Cage|Julianne Moore|Jessica Biel|Thoma...,Lee Tamahori,"If you can see the future, you can save it.",Las Vegas showroom magician Cris Johnson has a...,96,Action|Science Fiction|Thriller,Paramount Pictures,4/24/2007,5.9,2007,-51788987
1623,tt0375173,60000000,13395939,Alfie,Jude Law|Marisa Tomei|Omar Epps|Jane Krakowski...,Charles Shyer,Meet a man who never met a woman he didn't love.,"In Manhattan, the British limousine driver Alf...",103,Comedy,Paramount Pictures,10/22/2004,5.4,2004,-46604061
1631,tt0315297,50000000,25195000,Twisted,Ashley Judd|Samuel L. Jackson|Andy GarcÃ­a|Dav...,Philip Kaufman,Every murder has a mark.,Recently promoted and transferred to the homic...,97,Action|Adventure|Crime|Drama|Thriller,Paramount Pictures,2/27/2004,5.7,2004,-24805000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
730,tt1229238,145000000,694713380,Mission: Impossible - Ghost Protocol,Tom Cruise|Jeremy Renner|Simon Pegg|Paula Patt...,Brad Bird,No Plan. No Backup. No Choice.,In the 4th installment of the Mission Impossib...,133,Action|Thriller|Adventure,Paramount Pictures,12/7/2011,6.7,2011,549713380
1738,tt0418279,150000000,709709780,Transformers,Shia LaBeouf|Josh Duhamel|Megan Fox|Rachael Ta...,Michael Bay,Their war. Our world.,"Young teenager, Sam Witwicky becomes involved ...",144,Adventure|Science Fiction|Action,Paramount Pictures,6/27/2007,6.6,2007,559709780
603,tt0367882,185000000,786636033,Indiana Jones and the Kingdom of the Crystal S...,Harrison Ford|Cate Blanchett|Shia LaBeouf|Ray ...,Steven Spielberg,The adventure continues . . .,"Set during the Cold War, the Soviets â€“ led b...",122,Adventure|Action,Paramount Pictures,5/21/2008,5.6,2008,601636033
317,tt1055369,150000000,836297228,Transformers: Revenge of the Fallen,Shia LaBeouf|Megan Fox|Josh Duhamel|Rainn Wils...,Michael Bay,Revenge is coming,Sam Witwicky leaves the Autobots behind for a ...,150,Science Fiction|Action|Adventure,Paramount Pictures,6/19/2009,6.0,2009,686297228
828,tt1399103,195000000,1123746996,Transformers: Dark of the Moon,Shia LaBeouf|John Malkovich|Ken Jeong|Frances ...,Michael Bay,The invasion we always feared. An enemy we nev...,Sam Witwicky takes his first tenuous steps int...,154,Action|Science Fiction|Adventure,Paramount Pictures,6/28/2011,6.1,2011,928746996

Вопрос 19. Какой год стал самым успешным по суммарным кассовым сборам?

In [26]:
data19 = pd.read_csv('movie_bd_v5.csv')
data19.groupby(['release_year'])['revenue'].sum().sort_values(ascending=False)

release_year
2015    25449202382
2014    23405862953
2013    23213799791
2012    23079001687
2011    22676791872
2010    21071204961
2009    20261791024
2008    18252781990
2007    18162406801
2004    15663430720
2005    15309425558
2006    14775042320
2003    14346123312
2002    14136361487
2001    13017764865
2000    10664099805
Name: revenue, dtype: int64

Вопрос 20. Какой самый прибыльный год для студии Warner Bros?

In [27]:
data20 = pd.read_csv('movie_bd_v5.csv')
data20['production_companies'] = data20['production_companies'].str.split('|')
data20 = data20.explode('production_companies')
data20[data20['production_companies'].str.contains('Warner Bros')].groupby(['release_year'])['revenue'].sum().sort_values(ascending=False)

release_year
2014    3246549646
2007    3183675217
2008    3050595031
2010    3008712985
2011    2845393682
2003    2814008221
2009    2737954136
2004    2731933725
2013    2599953400
2005    2412980298
2001    2280142579
2012    1869520056
2002    1702709901
2015    1691168351
2006    1576351872
2000    1025531386
Name: revenue, dtype: int64

Вопрос 21. В каком месяце за все годы суммарно вышло больше всего фильмов?

In [28]:
data21 = pd.read_csv('movie_bd_v5.csv')
data21['release_date'] = data21['release_date'].str.split('/')
month = []
for i in data21['release_date']:
    month.append(i[0])
c = Counter(month)    
print(c)

Counter({'9': 227, '12': 190, '10': 186, '8': 161, '3': 156, '4': 149, '6': 147, '11': 146, '7': 142, '5': 140, '2': 135, '1': 110})

Вопрос 22. Сколько суммарно вышло фильмов летом (за июнь, июль, август)?

In [29]:
summer = c['6']+ c['7']+ c['8']
print(summer)

450

Вопрос 23. Для какого режиссера зима — самое продуктивное время года?

In [30]:
data23 = pd.read_csv('movie_bd_v5.csv')
data23['director'] = data23['director'].str.split('|')
data23 = data23.explode('director')
data23['release_date'] = data23['release_date'].str.split('/')
month = []
for i in data23['release_date']:
    month.append(i[0])
data23['month'] = month
data23[data23['month'].isin(['1', '2', '12'])].groupby(['director'])['month'].count().sort_values(ascending=False)

director
Peter Jackson            7
Steven Soderbergh        6
Clint Eastwood           6
Martin Scorsese          4
Adam Shankman            4
                        ..
Matt Bettinelli-Olpin    1
Matt Reeves              1
Matthew O'Callaghan      1
Matthew Vaughn           1
Jon Avnet                1
Name: month, Length: 358, dtype: int64

Вопрос 24. Какая студия даёт самые длинные названия своим фильмам по количеству символов?

In [31]:
data24 = pd.read_csv('movie_bd_v5.csv')
data24['production_companies'] = data24['production_companies'].str.split('|')
data24 = data24.explode('production_companies')
data24['title_len'] = data24['original_title'].apply(len)
data24.groupby(['production_companies'])['title_len'].mean().sort_values(ascending=False)

production_companies
Four By Two Productions       83.0
Jim Henson Company, The       59.0
Dos Corazones                 47.0
Museum Canada Productions     46.0
Polsky Films                  46.0
                              ...
Everest Entertainment          3.0
Berlanti Productions           3.0
XM2 Productions                2.0
Ixtlan Productions             2.0
Global Entertainment Group     2.0
Name: title_len, Length: 1771, dtype: float64

Вопрос 25. Описания фильмов какой студии в среднем самые длинные по количеству слов?

In [32]:
data25 = pd.read_csv('movie_bd_v5.csv')
data25['production_companies'] = data25['production_companies'].str.split('|')
data25 = data25.explode('production_companies')
data25['overview_len'] = data25['overview'].apply(len)
data25.groupby(['production_companies'])['overview_len'].mean().sort_values(ascending=False)

production_companies
Midnight Picture Show                    1000.0
Room 9 Entertainment                      964.0
Brookwell-McNamara Entertainment          936.0
Lions Gate Family Entertainment           909.0
Crest Animation Productions               909.0
                                          ...
Projection Pictures                        74.0
London Boulevard                           74.0
Phantom Four                               72.0
Empire Pictures                            62.0
Motion Picture Corporation of America      59.0
Name: overview_len, Length: 1771, dtype: float64

Вопрос 26. Какие фильмы входят в один процент лучших по рейтингу?

In [51]:
data26 = pd.read_csv('movie_bd_v5.csv')
top_rate = np.quantile(data26a['vote_average'], 0.99)
display(top_rate)
data26[data26['vote_average'] >= top_rate].groupby(['original_title'])['vote_average'].sum().sort_values(ascending=False)

7.8

original_title
The Dark Knight                                      8.1
Inside Out                                           8.0
Interstellar                                         8.0
Room                                                 8.0
The Imitation Game                                   8.0
Gone Girl                                            7.9
Memento                                              7.9
The Wolf of Wall Street                              7.9
Guardians of the Galaxy                              7.9
12 Years a Slave                                     7.9
Inception                                            7.9
The Lord of the Rings: The Return of the King        7.9
The Pianist                                          7.9
The Grand Budapest Hotel                             7.9
Eternal Sunshine of the Spotless Mind                7.8
Dallas Buyers Club                                   7.8
Her                                                  7.8
Big Hero 6                                           7.8
3 Idiots                                             7.8
There Will Be Blood                                  7.8
Mr. Nobody                                           7.8
Spotlight                                            7.8
The Fault in Our Stars                               7.8
The Lord of the Rings: The Fellowship of the Ring    7.8
The Lord of the Rings: The Two Towers                7.8
The Prestige                                         7.8
The Theory of Everything                             7.8
Prisoners                                            7.8
Name: vote_average, dtype: float64

In [45]:
data26a = pd.read_csv('movie_bd_v5.csv')
top_rate_a = data26a['vote_average'].value_counts(bins=100).sort_index(ascending=False)
display(top_rate)
data26a.loc[(data26a['vote_average'] >= top_rate_a.index[4].left) & (data26a['vote_average'] <= top_rate_a.index[0].right)]

(8.052, 8.1]      1
(8.004, 8.052]    0
(7.956, 8.004]    4
(7.908, 7.956]    0
(7.86, 7.908]     9
                 ..
(3.492, 3.54]     2
(3.444, 3.492]    0
(3.396, 3.444]    2
(3.348, 3.396]    0
(3.294, 3.348]    2
Name: vote_average, Length: 100, dtype: int64

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year
9,tt2096673,175000000,853708609,Inside Out,Amy Poehler|Phyllis Smith|Richard Kind|Bill Ha...,Pete Docter,Meet the little voices inside your head.,"Growing up can be a bumpy road, and it's no ex...",94,Comedy|Animation|Family,Walt Disney Pictures|Pixar Animation Studios|W...,6/9/2015,8.0,2015
34,tt3170832,6000000,35401758,Room,Brie Larson|Jacob Tremblay|Joan Allen|Sean Bri...,Lenny Abrahamson,Love knows no boundaries,Jack is a young boy of 5 years old who has liv...,117,Drama|Thriller,Element Pictures|No Trace Camping|A24|Duperele...,10/16/2015,8.0,2015
118,tt0816692,165000000,621752480,Interstellar,Matthew McConaughey|Jessica Chastain|Anne Hath...,Christopher Nolan,Mankind was born on Earth. It was never meant ...,Interstellar chronicles the adventures of a gr...,169,Adventure|Drama|Science Fiction,Paramount Pictures|Legendary Pictures|Warner B...,11/5/2014,8.0,2014
119,tt2015381,170000000,773312399,Guardians of the Galaxy,Chris Pratt|Zoe Saldana|Dave Bautista|Vin Dies...,James Gunn,All heroes start somewhere.,"Light years from Earth, 26 years after being a...",121,Action|Science Fiction|Adventure,Marvel Studios|Moving Picture Company (MPC)|Bu...,7/30/2014,7.9,2014
125,tt2084970,14000000,233555708,The Imitation Game,Benedict Cumberbatch|Keira Knightley|Matthew G...,Morten Tyldum,The true enigma was the man who cracked the code.,Based on the real life story of legendary cryp...,113,History|Drama|Thriller|War,Black Bear Pictures|Bristol Automotive,11/14/2014,8.0,2014
128,tt2267998,61000000,369330363,Gone Girl,Ben Affleck|Rosamund Pike|Carrie Coon|Neil Pat...,David Fincher,You don't know what you've got 'til it's...,With his wife's disappearance having become th...,145,Mystery|Thriller|Drama,Twentieth Century Fox Film Corporation|Regency...,10/1/2014,7.9,2014
138,tt2278388,30000000,174600318,The Grand Budapest Hotel,Ralph Fiennes|Tony Revolori|F. Murray Abraham|...,Wes Anderson,A perfect holiday without leaving home.,The Grand Budapest Hotel tells of a legendary ...,99,Comedy|Drama,Fox Searchlight Pictures|Scott Rudin Productio...,2/26/2014,7.9,2014
370,tt1375666,160000000,825500000,Inception,Leonardo DiCaprio|Joseph Gordon-Levitt|Ellen P...,Christopher Nolan,Your mind is the scene of the crime.,"Cobb, a skilled thief who commits corporate es...",148,Action|Thriller|Science Fiction|Mystery|Adventure,Legendary Pictures|Warner Bros.|Syncopy,7/14/2010,7.9,2010
599,tt0468569,185000000,1001921825,The Dark Knight,Christian Bale|Michael Caine|Heath Ledger|Aaro...,Christopher Nolan,Why So Serious?,Batman raises the stakes in his war on crime. ...,152,Drama|Action|Crime|Thriller,DC Comics|Legendary Pictures|Warner Bros.|Syncopy,7/16/2008,8.1,2008
872,tt0253474,35000000,120072577,The Pianist,Adrien Brody|Thomas Kretschmann|Frank Finlay|M...,Roman Polanski,Music was his passion. Survival was his master...,The Pianist is a film adapted from the biograp...,150,Drama|War,Bac Films|Canal+Polska|Heritage Films|Studio B...,9/24/2002,7.9,2002
1081,tt0167260,94000000,1118888979,The Lord of the Rings: The Return of the King,Elijah Wood|Ian McKellen|Viggo Mortensen|Liv T...,Peter Jackson,The eye of the enemy is moving.,Aragorn is revealed as the heir to the ancient...,201,Adventure|Fantasy|Action,WingNut Films|New Line Cinema,12/1/2003,7.9,2003
1183,tt0993846,100000000,392000694,The Wolf of Wall Street,Leonardo DiCaprio|Jonah Hill|Margot Robbie|Kyl...,Martin Scorsese,EARN. SPEND. PARTY.,A New York stockbroker refuses to cooperate in...,180,Crime|Drama|Comedy,Paramount Pictures|Appian Way|EMJAG Production...,12/25/2013,7.9,2013
1191,tt2024544,20000000,187000000,12 Years a Slave,Chiwetel Ejiofor|Michael Fassbender|Lupita Nyo...,Steve McQueen,The extraordinary true story of Solomon Northup,"In the pre-Civil War United States, Solomon No...",134,Drama|History,Plan B Entertainment|Regency Enterprises|River...,10/18/2013,7.9,2013
1800,tt0209144,9000000,39723096,Memento,Guy Pearce|Carrie-Anne Moss|Joe Pantoliano|Mar...,Christopher Nolan,Some memories are best forgotten.,Suffering short-term memory loss after a head ...,113,Mystery|Thriller,Summit Entertainment|Newmarket Capital Group|T...,10/11/2000,7.9,2000

Вопрос 27. Какие актеры чаще всего снимаются в одном фильме вместе?

In [100]:
from itertools import combinations
data27 = pd.read_csv('movie_bd_v5.csv')
data27['cast'] = data27['cast'].str.split('|')
data27['combinations'] = data27['cast'].apply(lambda r: list(combinations(r, 2)))
data27 = data27.explode('combinations')
data27.groupby(['combinations'])['combinations'].count().sort_values(ascending=False)

combinations
(Daniel Radcliffe, Emma Watson)             8
(Daniel Radcliffe, Rupert Grint)            8
(Rupert Grint, Emma Watson)                 7
(Ben Stiller, Owen Wilson)                  6
(Johnny Depp, Helena Bonham Carter)         6
                                           ..
(Matthew McConaughey, Rene Russo)           1
(Matthew McConaughey, Reese Witherspoon)    1
(Matthew McConaughey, Powers Boothe)        1
(Matthew McConaughey, PenÃ©lope Cruz)       1
(50 Cent, Adewale Akinnuoye-Agbaje)         1
Name: combinations, Length: 18121, dtype: int64

# Предобработка

In [34]:
answers = {} # создадим словарь для ответов

# тут другие ваши предобработки колонок например:

#the time given in the dataset is in string format.
#So we need to change this in datetime format
# ...

# 1. У какого фильма из списка самый большой бюджет?

Использовать варианты ответов в коде решения запрещено.    
Вы думаете и в жизни у вас будут варианты ответов?)

In [35]:
# в словарь вставляем номер вопроса и ваш ответ на него
# Пример: 
answers['1'] = '2. Spider-Man 3 (tt0413300)'
# запишите свой вариант ответа
answers['1'] = '...'
# если ответили верно, можете добавить комментарий со значком "+"

In [36]:
# тут пишем ваш код для решения данного вопроса:

ВАРИАНТ 2

In [37]:
# можно добавлять разные варианты решения

# 2. Какой из фильмов самый длительный (в минутах)?

In [38]:
# думаю логику работы с этим словарем вы уже поняли, 
# по этому не буду больше его дублировать
answers['2'] = '...'

# 3. Какой из фильмов самый короткий (в минутах)?

# 4. Какова средняя длительность фильмов?

# 5. Каково медианное значение длительности фильмов?

# 6. Какой самый прибыльный фильм?
#### Внимание! Здесь и далее под «прибылью» или «убытками» понимается разность между сборами и бюджетом фильма. (прибыль = сборы - бюджет) в нашем датасете это будет (profit = revenue - budget)

In [39]:
# лучше код получения столбца profit вынести в Предобработку что в начале

# 7. Какой фильм самый убыточный?

# 8. У скольких фильмов из датасета объем сборов оказался выше бюджета?

# 9. Какой фильм оказался самым кассовым в 2008 году?

# 10. Самый убыточный фильм за период с 2012 по 2014 г. (включительно)?

# 11. Какого жанра фильмов больше всего?

In [40]:
# эту задачу тоже можно решать разными подходами, попробуй реализовать разные варианты
# если будешь добавлять функцию - выноси ее в предобработку что в начале

ВАРИАНТ 2

# 12. Фильмы какого жанра чаще всего становятся прибыльными?

# 13. У какого режиссера самые большие суммарные кассовые сбооры?

# 14. Какой режисер снял больше всего фильмов в стиле Action?

# 15. Фильмы с каким актером принесли самые высокие кассовые сборы в 2012 году?

# 16. Какой актер снялся в большем количестве высокобюджетных фильмов?

# 17. В фильмах какого жанра больше всего снимался Nicolas Cage?

# 18. Самый убыточный фильм от Paramount Pictures

# 19. Какой год стал самым успешным по суммарным кассовым сборам?

# 20. Какой самый прибыльный год для студии Warner Bros?

# 21. В каком месяце за все годы суммарно вышло больше всего фильмов?

# 22. Сколько суммарно вышло фильмов летом? (за июнь, июль, август)

# 23. Для какого режиссера зима – самое продуктивное время года?

# 24. Какая студия дает самые длинные названия своим фильмам по количеству символов?

# 25. Описание фильмов какой студии в среднем самые длинные по количеству слов?

# 26. Какие фильмы входят в 1 процент лучших по рейтингу? 
по vote_average

# 27. Какие актеры чаще всего снимаются в одном фильме вместе?

ВАРИАНТ 2

# Submission

In [41]:
# в конце можно посмотреть свои ответы к каждому вопросу
answers

{'1': '...', '2': '...'}

In [42]:
# и убедиться что ни чего не пропустил)
len(answers)

2